version: "3"
services:
  mysql:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./ops/db/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: clean_architecture_go_v2
      MYSQL_DATABASE: clean_architecture_go_v2
      MYSQL_USER: clean_architecture_go_v2
      MYSQL_PASSWORD: clean_architecture_go_v2
    ports:
      - "3306:3306"
    container_name: clean-architecture-go-v2-mysql
    network_mode: "bridge"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: clean-architecture-go-v2-grafana
    network_mode: "bridge"
    depends_on:
      - prometheus
      - prometheus-pushgateway
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    container_name: clean-architecture-go-v2-prometheus
    network_mode: "bridge"
  prometheus-pushgateway:
    image: prom/pushgateway
    container_name: clean-architecture-go-v2-pushgateway
    expose:
      - 9091
    ports:
      - "9091:9091"
